name: delern_flutter
description: Spaced repetition learning system (Flutter version)

# Version information is set by Fastlane when building:
# $ flutter build --build-name=... --build-number=...
# We set a default here for debugging purposes because debug binary is not
# usually built via Fastlane.
version: 1.0.0+1

dependencies:
  device_info: ^0.4.0
  package_info: ^0.4.0
  url_launcher: ^5.0.1
  flutter_markdown: ^0.3.2
  http: ^0.12.0
  share: ^0.6.0
  shared_preferences: ^0.5.1
  quiver: ">=2.0.0 <3.0.0"
  built_collection: ^4.2.2
  built_value: ^6.6.0
  rxdart: ^0.23.1
  uuid: ^2.0.1

  flutter_sentry: ^0.4.0
  # Needed for the User context type, version is bound by flutter_sentry.
  sentry: any

  image_picker: ^0.6.1
  # https://github.com/renefloor/flutter_cached_network_image/issues/261
  cached_network_image: 2.0.0-rc
  app_settings: ^4.0.0
  firebase_auth: ^0.15.3
  firebase_analytics: ^5.0.9
  firebase_database: ^3.1.1
  firebase_messaging: ^6.0.9
  firebase_remote_config: ^0.3.0
  firebase_storage: ^3.1.1
  firebase_performance: ^0.3.1

  google_sign_in: ^4.0.1
  flutter_facebook_login: ^3.0.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  intl_translation: ^0.17.3
  mockito: ^3.0.0
  pedantic: ^1.0.0
  build_runner: ^1.6.1
  built_value_generator: ^6.6.0
  test: ^1.6.2

# Uncomment the following to override any dependency.
#dependency_overrides:
#  flutter_sentry:
#    path: ../../flutter_sentry/

flutter:
  uses-material-design: true

  assets:
    # Onboarding.
    - images/card_sharing.png
    - images/child_learning.png
    - images/deck_creation.png

    # Icons for Sign In buttons and Navigation Drawer.
    - images/anonymous.jpg
    - images/google_sign_in.png
    - images/facebook_sign_in.png

    # Image for login screen
    - images/delern_with_logo.png

    # Logo to display in e.g. About dialog.
    - images/ic_launcher.png
# Disable builders for now because it breaks builds (need "flutter clean" all
# the time) and debug mode (breakpoints are not triggering).
# This means that after each change to BuiltValue we have to run
# "bundle exec fastlane generate".
#
# builders:
#   built_value_generator: any
