name: delern_flutter
description: Spaced repetition learning system (Flutter version)

# Version information is set by Fastlane when building:
# $ flutter build --build-name=... --build-number=...
# We set a default here for debugging purposes because debug binary is not
# usually built via Fastlane.
version: 1.0.0+1

dependencies:
  device_info: ^0.4.0
  package_info: ^0.4.0
  url_launcher: ^5.0.1
  flutter_markdown: ^0.4.0
  http: ^0.12.0
  share: ^0.6.0
  shared_preferences: ^0.5.1
  quiver: ">=2.0.0 <3.0.0"
  built_collection: ^4.3.2
  built_value: ^7.1.0
  rxdart: ^0.23.1
  uuid: ^2.0.1

  flutter_sentry: ^0.4.1
  # Needed for the User context type, version is bound by flutter_sentry.
  sentry: any

  image_picker: ^0.6.1
  # https://github.com/renefloor/flutter_cached_network_image/issues/261
  cached_network_image: 2.0.0-rc
  app_settings: ^4.0.0
  firebase_auth: ^0.15.3
  firebase_analytics: ^5.0.9
  firebase_database: ^3.1.1
  firebase_messaging: ^6.0.9
  firebase_remote_config: ^0.3.0
  firebase_storage: ^3.1.1
  firebase_performance: ^0.3.1

  google_sign_in: ^4.0.1
  flutter_facebook_login: ^3.0.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  intl_translation: ^0.17.3
  mockito: ^3.0.0
  pedantic: ^1.0.0
  build_runner: ^1.10.0
  built_value_generator: any
  test: ^1.15.2

dependency_overrides:
# Uncomment the following to override any dependency.
#  flutter_sentry:
#    path: ../../flutter_sentry/

flutter:
  uses-material-design: true

  assets:
    - images/
