name: fastlane update

on:
  schedule:
    # Every day at 3:04 UTC: https://crontab.guru/#4_3_*_*_*
    - cron: "4 3 * * *"

jobs:
  fastlane-update:
    # Do not run on forks.
    if: "github.repository == 'dasfoo/delern'"
    env:
      # Make it an environment variable because it's also used by "hub".
      GITHUB_TOKEN: ${{ secrets.FASTLANE_UPDATE_GITHUB_TOKEN }}
      UPDATE_BRANCH: automated-update
      # The default SDK directory created by fastlane-plugin-flutter is
      # vendor/flutter under application root, which likely confuses flutter
      # cocoapods integration. Reroute here, and debug when we have spare time.
      FLUTTER_ROOT: /tmp/flutter
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: "Install dependencies"
        run: |
          gem environment
          gem install bundler --no-doc
          bundle install
          bundle console <<<RUBY_VERSION
      - name: "Install artifacts so that Flutter app can be built (for Pods)"
        working-directory: flutter
        run: bundle exec fastlane install_debug_keys
      - name: "Fastlane Update"
        run: bundle exec fastlane update
      - name: "Check for changes and create/update PR"
        run: |
          git config \
              url."https://dotdoom:${GITHUB_TOKEN?}@github.com/".insteadOf \
              'https://github.com/'

          if [ -n "$(git status --porcelain)" ]; then
            git checkout -b "${UPDATE_BRANCH?}"
            git add .
            git diff --cached
            git commit --message "[auto] update dependencies"
            git push -f origin HEAD

            brew install hub
            # If PR already exists, hub exits with code 1 (just like any other
            # failure). Ignore it.
            hub pull-request --labels dependencies --no-edit || true
          else
            # Delete branch when there are no changes (e.g. to close PR), ignore
            # if it does not exist.
            git push origin ":${UPDATE_BRANCH?}" || true
          fi
