name: Fastlane Update

on:
  schedule:
    # Every Saturday at [3:04] UTC: https://crontab.guru/#4_3_*_*_SAT
    - cron: "4 3 * * SAT"

jobs:
  fastlane-update:
    # Do not run on forks.
    if: "github.repository == 'dasfoo/delern'"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install dependencies"
        run: bundle install
      - name: "Fastlane Update"
        run: bundle exec fastlane update
      - name: "Check for changes and create/update PR"
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config url."https://api:${GITHUB_TOKEN?}@github.com/".insteadOf 'https://github.com/'

            git checkout -b automated-update
            git add .
            git commit --message "[auto] update dependencies"
            git push -f origin HEAD

            brew install hub
            # If PR already exists, hub exits with code 1 (just like any other
            # failure). Ignore it.
            hub pull-request --no-edit || true
          fi
