name: firebase

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*.*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          # Keep in sync with "engines.node" in package.json.
          node-version: 10
      # On Windows, npm is 5.6 and "npm ci" was introduced in 5.7.
      - run: npm install -g npm@latest
      # Have to split into steps because Windows can't handle multiple commands.
      - run: npm ci
        working-directory: firebase
      - run: npm run check
        working-directory: firebase
      # "compile" is run by "npm install" (i.e. "npm ci").
      - run: npm ci
        working-directory: firebase/functions
      - run: npm run check
        working-directory: firebase/functions
      # Run firebase-bolt just to verify that the rules parse. Since it always
      # creates output, redirect it to a temporary file to keep Git tree clean.
      - run: node_modules/.bin/firebase-bolt database.rules.bolt -o ../../../nothing
        working-directory: firebase

  publish:
    if: >
      startsWith(github.repository, 'dasfoo/') &&
      github.event_name == 'push'
    needs: build
    env:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: npm ci
        working-directory: firebase
      - run: npm ci
        working-directory: firebase/functions

      - run: npm run deploy
        working-directory: firebase
        env:
          PROJECT: delern-debug

      - run: npm run deploy
        working-directory: firebase
        env:
          PROJECT: delern-e1b33
